versioin: 2

sources:
  - name: staging
    description: "Raw data sources for NYC taxi rides"
    database: taxi_rides_ny # Or name of your GCP project
    schema: prod # Or name of your BigQuery dataset 
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
